//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIOSEC.Pages.Ventas
{


    public partial class WF_Administrar_Pedido_De_Ventas
    {
    }
}
